#!/bin/sh
#
# Run the docs build process twice, producing `build/latest` and
# `build/stable` instead of `docs/_build`.

set -e


latest_branch=main
stable_tag=$(git tag --sort=version:refname | tail -1)

do_build() {
    git checkout "$1"
    export SECUREDROP_DOCS_RELEASE="$2"

    make html
    # Remote-loaded SVGs will cause a build failure unless we use force-mode.
    LATEXMKOPTS="-interaction=nonstopmode -f" make latexpdf || true

    mkdir -p build
    mv docs/_build "build/${2}"
}

do_build "$stable_tag" stable
do_build "$latest_branch" latest
