---
name: Publish

on:
  push:
    branches: ["main"]
    tags: ["**"]  # run for all tags

env:
  DEFAULT_BRANCH: main

jobs:
  build:
    name: Build
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: "."
      containerfile: deploy/Dockerfile
      build-args: |
        GIT_BRANCH=${{ github.sha }}
      registry: ghcr.io/freedomofpress/securedrop-docs
      requires-deep-history: true
      add-branch-tags: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  notify:
    uses: freedomofpress/actionslib/.github/workflows/update-k8s-trigger.yaml@main
    needs:
    - build
    if: ${{ needs.build.result == 'success' && github.ref_name == 'main' }}
    strategy:
      fail-fast: false
      matrix:
        cluster:
        - production
        - staging
    permissions:
      contents: read
      actions: read
      pull-requests: read
    with:
      trigger: sdo-docs/${{ matrix.cluster }}
      sha: ${{ github.sha }}
    secrets:
      local-token: ${{ secrets.GITHUB_TOKEN }}
      k8s-configs-token: ${{ secrets.K8S_CONFIGS_GITHUB_TOKEN }}
